
name: "Update data source"

on:
  push:
  pull_request:
  schedule:
    # Every Sunday at 03:58
    - cron: '58 3 * * 0'

jobs:
  update-data-source:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Show data source package details
        run: composer show mledoze/countries

      - name: Compile data source
        run: composer compile-data-source

      - name: Execute tests
        run: composer test

      - name: Create PR for the release branch
        run: gh pr create --base master --title "[$(date +%F)] Update data source" --body "Update data source to the latest version."

      #- name: Set the newly created PR to auto merge
      #  run: gh pr merge --auto --merge
